apiVersion: v1
kind: Pod
metadata:
  name: s3-debug-awscli
  namespace: openshift-operators
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containers:
  - name: s3-debug-awscli
    image: amazon/aws-cli
    command: ["/bin/sh"]
    stdin: true
    tty: true

    env:
    - name: HOME
      value: /home/nonroot
    - name: AWS_CA_BUNDLE
      value: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

    workingDir: /home/nonroot

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL

    volumeMounts:
    - name: home
      mountPath: /home/nonroot

    # Mount CA bundle at the exact file path
    - name: trusted-ca
      mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      subPath: tls-ca-bundle.pem
      readOnly: true

  volumes:
  - name: home
    emptyDir: {}

  - name: trusted-ca
    configMap:
      name: openshift-trusted-cabundle
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem